// Map of specialty acronyms to full specialty names (case-insensitive keys)
const specialtyAcronymMap = {
			obgyn: "Obstetrics and Gynecology",
			"obstetrics": "Obstetrics and Gynecology",
			"gynecology": "Obstetrics and Gynecology",
			"women's health": "Obstetrics and Gynecology",
			ent: "Otolaryngology",
			"ear nose throat": "Otolaryngology",
			"sinus": "Otolaryngology",
			pcp: ["Primary Care", "Internal Medicine", "Family Medicine, Primary Care Grp/Prac"],
				"primary care": ["Primary Care", "Internal Medicine", "Family Medicine, Primary Care Grp/Prac"],
                "primary": ["Primary Care", "Internal Medicine", "Family Medicine, Primary Care Grp/Prac"],
				"general practice": ["Primary Care", "Family Medicine, Primary Care Grp/Prac"],
				"family doctor": ["Family Medicine", "Primary Care, Primary Care Grp/Prac"],
				"family medicine": ["Family Medicine", "Primary Care, Primary Care Grp/Prac"],
				"internal medicine": ["Internal Medicine", "Primary Care, Primary Care Grp/Prac"],
			gi: "Gastroenterology",
			"digestive": "Gastroenterology",
			"stomach": "Gastroenterology",
			cardio: "Cardiology",
			"heart": "Cardiology",
			"cardiologist": "Cardiology",
			derm: "Dermatology",
			"skin": "Dermatology",
			"rash": "Dermatology",
			ped: "Pediatrics",
			"children": "Pediatrics",
			"kids": "Pediatrics",
			ortho: "Orthopedics",
			"bones": "Orthopedics",
			"joints": "Orthopedics",
			uro: "Urology",
			"urinary": "Urology",
			"bladder": "Urology",
			neph: "Nephrology",
			"kidney": "Nephrology",
			rheum: "Rheumatology",
			"arthritis": "Rheumatology",
			psych: "Psychiatry",
			"mental health": "Psychiatry",
			"depression": "Psychiatry",
			pulm: "Pulmonology",
			"lung": "Pulmonology",
			"asthma": "Pulmonology",
			heme: "Hematology",
			"blood": "Hematology",
			onco: "Oncology",
			"cancer": "Oncology",
			endo: "Endocrinology",
			"diabetes": "Endocrinology",
			ophtho: "Ophthalmology",
			"eye": "Ophthalmology",
			rad: "Radiology",
			"imaging": "Radiology",
			path: "Pathology",
			"lab": "Pathology",
			em: "Emergency Medicine",
			"er": "Emergency Medicine",
			fm: "Family Medicine",
			"family doctor": "Family Medicine",
			im: "Internal Medicine",
			"adult medicine": "Internal Medicine",
			gs: "General Surgery",
			"surgery": "General Surgery",
			ns: "Neurosurgery",
			"brain surgery": "Neurosurgery",
			// Add more as needed
};

export default specialtyAcronymMap;
